name: flutter_breadcrumb
description: Flutter Widget that can easily create Breadcrumb in Flutter.
version: 0.1.2
repository: https://github.com/payam-zahedi/flutter_breadcrumb
issue_tracker: https://github.com/payam-zahedi/flutter_breadcrumb/issues
homepage: https://github.com/payam-zahedi/flutter_breadcrumb

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
